server:
  port: 9001
spring:
  application:
    name: sa-token-auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_alibaba?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.lengqi.cloud.token.entity