server:
  port: 9001
spring:
  application:
    name: sa-token-auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sa_token_cloud?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

logging:
  level:
    com.lengqi.cloud.admin.feign.*: debug

#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000